#!/usr/bin/env bash
echo "pre commit hook start"

echo "init tests and phpstan"
bash -c "composer tests && composer run php-stan" || exit 1

CHANGED_FILES=$(git diff --cached  --name-only --diff-filter=ACM -- '*.php' | tr '\n' ' ')
if [ -n "$CHANGED_FILES" ]; then
   echo "init php-fixer"
   bash -c "vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php $CHANGED_FILES; git add $CHANGED_FILES;"
   echo "finish tests and php-fixer"
fi
   echo "pre commit hook finish"